chore: Attach workspace in lib as expected
The git release script in tag raises an error:

    Error: open lib/drafter.js: no such file or directory

This looks like it is because workspace isn't attached inside lib